### ISSUE TITLE
Error on publish Uncaught TypeError: Cannot set property Promise of #<Window>

### ISSUE THREAD

**Issue by FullCr0** [xdan/jodit#1037]
**Jodit Version:**  3.24.5

**Browser:**  Chrome/IE/Firefox
**OS:**  Windows
**Is React App:**  True

**Expected behavior:**
I'm building a Power Component Framework (PCF) for Canvas Power Apps using the Jodit

When I run tests, it works fine, as shown in the image below.
![image](https://github.com/xdan/jodit/assets/149505298/bb66cce8-6002-4091-8d86-1ad13f243dc7)

I execute the 'msbuild' command and export it to the environment, and there are no errors. 

**Actual behavior:**
However, when I try to use it within the application, it throws the following error:

```
Uncaught TypeError: Cannot set property Promise of #<Window> which has only a getter
    at L.polyfill (jodit.min.js:1:156302)
    at Object._ (jodit.min.js:1:150259)
    at n (jodit.min.js:1:721786)
    at Object._ (jodit.min.js:1:715095)
    at n (jodit.min.js:1:721786)
    at eval (jodit.min.js:1:723193)
    at eval (jodit.min.js:1:723889)
    at eval (jodit.min.js:1:723900)
    at eval (jodit.min.js:1:39)
    at eval (jodit.min.js:1:62)
```

![image](https://github.com/xdan/jodit/assets/149505298/b58cb35a-12a8-4f1e-9b7c-6820114abaca)

Could you please help me if I'm doing something wrong?
If you need any more information, I'm available.
Thank you!

**Comment by xdan** [comment]
I think your problem is with the es6-promise/auto library
For some reason, something in your code prohibited changing window.Promise
window.Promise = function () {}
It should work in any browser

**Comment by xdan** [comment]
**Root cause:** the error comes from the `es6-promise` polyfill (`window.Promise = …`), which is bundled **only in the es5 (IE11) build**. The Power Apps Canvas sandbox freezes `window.Promise` as a getter-only property, so any reassignment throws `Cannot set property Promise of #<Window> which has only a getter`.

**Fix:** use a **modern build** instead of the es5 one — Power Apps Canvas runs modern Chromium and doesn't need any polyfills:

```js
import { Jodit } from 'jodit/esm';          // or
import { Jodit } from 'jodit/es2021/jodit.min.js';
```

The es2018/es2021/esm builds contain **no** Promise polyfill, so the frozen-window assignment never happens. The es5 build is legacy (IE11) and shouldn't be used in a modern PCF.

Closing — the modern builds resolve this; reopen if you specifically need the es5 build in that environment.
