### ISSUE TITLE
Table dragging creates an issue

### ISSUE THREAD

**Issue by MyMonsterVR** [xdan/jodit#1128]
**Jodit Version:**  3.4.5

**Browser:** Chromium
**OS:** Windows
**Is React App:** False

**Code**

```
Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Function.value (4991.ffa7f32b.chunk.js:1:530892)
    at Function.value (4991.ffa7f32b.chunk.js:1:530723)
    at t.value (4991.ffa7f32b.chunk.js:1:523464)
    at t.value (4991.ffa7f32b.chunk.js:1:724843)
    at t.value (4991.ffa7f32b.chunk.js:1:724678)
    at y (4991.ffa7f32b.chunk.js:1:282307)
```

**Expected behavior:**
Tables should be draggable

**Actual behavior:**
If you take a 2+ row and column table (2x2 and up) and merge the 2 columns together then if you press the "insert column before/after" button (your main buttons is broken, but thats another issue) then you will have a normal column, a column thats only exists on the top and the merged column (see attached image)
![image](https://github.com/xdan/jodit/assets/31127327/239707a9-80c7-4bac-89e0-3eaa4680aa10)

If you then try to drag the bugged one then it will give you the weak map key error

**Comment by xdan** [comment]
@MyMonsterVR Hi, please try in 4.2.27. Fixed several bugs
