### ISSUE TITLE
"Uncaught TypeError: Cannot redefine property: __activeTab" occurs when I use 'brush' button twice in inline-popup for `a` element.

### ISSUE THREAD

**Issue by mstssk** [xdan/jodit#815]
**Jodit Version:**  3.16.5

**Browser:**  Chrome 100.0.4896.60
**OS:**  macOS Monterey 12.3
**Is React App:**  False

**Code**

No specific configuration is required.

**Expected behavior:**

We can use the brush button in inline-popup form 'a' element multiple times.

**Actual behavior:**

When I use 'brush' button twice in inline-popup for 'a' element, Color picker widget does not shown.

This problem is also reproduced in the Playground at https://xdsoft.net/jodit/.

https://user-images.githubusercontent.com/500072/160816384-be5c7a95-365d-405c-b99d-159d9d786d86.mov

```
Uncaught TypeError: Cannot redefine property: __activeTab
    at Function.defineProperty (<anonymous>)
    at s (jodit.es2018.en.min.js:1:108254)
    at Object.popup (jodit.es2018.en.min.js:1:309310)
    at n.value (jodit.es2018.en.min.js:1:182426)
    at HTMLSpanElement.r (jodit.es2018.en.min.js:1:64166)
    at HTMLSpanElement.v (jodit.es2018.en.min.js:1:9422)
```

**Comment by mstssk** [comment]
@xdan Thank you!
I confirmed this issue is resolved in v3.16.6.
